In [1]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits

In [37]:
digit=load_digits()
x=(digit.data)
y=(digit.target)


In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
x_Std=StandardScaler().fit_transform(x)

In [28]:
x_Std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [104]:
from sklearn.decomposition import PCA
pca = PCA(n_components=40)

In [105]:
principalComponents = pca.fit_transform(x_Std)

In [106]:
principalDf = pd.DataFrame(data = principalComponents)

In [107]:
principalDf

0         1         2         3         4         5         6   \
0     1.914214 -0.954502 -3.946035  2.028724 -0.267173  0.530327 -1.415323   
1     0.588980  0.924636  3.924755 -1.779851 -0.993431 -0.675654  1.878569   
2     1.302039 -0.317189  3.023333 -2.043377 -2.081155  0.935121 -1.296197   
3    -3.020770 -0.868772 -0.801744 -2.187038 -0.556811  0.727124  0.959758   
4     4.528949 -1.093480  0.973121 -1.419509 -1.715105  1.431593  1.073645   
5    -1.301890 -1.148183 -1.574607 -2.413647 -0.630977  0.740804  1.306797   
6     1.434222 -2.957845  2.831278 -0.076952  0.523032  0.010903  0.983717   
7     0.614240  5.462184  0.658242  0.434429  0.850176 -0.954010 -1.833865   
8    -1.098451 -0.665823 -0.041023 -1.102525 -0.900724  0.755131 -0.966473   
9    -0.537970 -0.777492 -1.568922 -0.759984 -0.121343 -0.600988  0.675195   
10    3.378760 -0.495768 -2.280896  1.429204  0.006569 -0.150582 -0.739174   
11    2.063345  2.016679  1.540477 -4.773151 -2.194263  0.344461  3.084410   
12   -1.937011 -1.815247  2.801367 -0.786547  3.025775 -0.384552 -0.647714   
13   -3.258076  2.149124 -1.615648 -1.798926 -0.745366  1.828825  0.763421   
14    5.458744  0.025132  0.182527 -0.119621 -0.541032  0.104812  1.083108   
15   -3.877036  2.606816  1.858528  5.454027  0.615479  0.988485  3.602249   
16    0.921352 -3.262242  3.401443 -3.227336  1.096491  0.081960 -0.573135   
17    1.415335  1.954479  0.560574 -0.368825 -1.302536 -1.883617 -1.063238   
18   -0.926522  2.253018  1.532929  0.111958 -1.640290  0.261413 -0.069199   
19   -2.370963 -2.931915 -0.381362 -3.232762  2.084192  0.545310 -0.615773   
20    2.001901 -1.319746 -2.570949  0.855347 -0.565537 -1.017707 -0.811998   
21    1.694878  2.075387  0.885988 -4.388595 -1.446105 -0.307274  3.643110   
22   -3.114570 -1.058976  2.451496 -0.547892  0.761750 -0.012653 -1.890061   
23   -1.469418  3.910388 -2.078331 -0.869924  0.203791  0.689535 -0.288166   
24    4.003333 -0.322216  0.587683 -2.740556 -1.513544  0.676063  2.088566   
25   -0.376722  0.525118  1.356041  3.106102  0.926276 -1.029451  1.450079   
26    1.286726 -3.969443  2.542968  0.936670  0.282388  0.352676  1.026762   
27    3.842317  3.478237 -1.569506 -1.675844 -0.274118 -0.345103 -0.150011   
28   -0.166537  0.934111  1.259154 -0.086536 -1.045703  0.362902 -0.877884   
29   -2.014425 -2.376845 -0.707905 -3.515253  1.168346  0.694468  0.206819   
...        ...       ...       ...       ...       ...       ...       ...   
1767  4.958572 -1.159637  0.645671 -1.495314 -1.408072  0.580229  2.222100   
1768  1.009034 -3.325936 -0.584416  0.907491 -0.665940  0.398977 -1.279988   
1769 -0.542840 -0.492983 -3.138879  0.952805  0.732338 -1.169261  1.900085   
1770 -3.314656  1.510568 -0.820052 -1.838158 -1.474753  1.442502  2.178241   
1771  2.128214 -2.822365  3.623384 -1.087841 -0.085812  0.389349  1.443187   
1772 -1.814030  1.197999 -3.113638 -1.063800 -1.806721  0.021174  1.294922   
1773  1.374678 -4.417769  0.544578  0.931146  1.151819 -0.342557  0.125670   
1774  0.762953  0.643399  3.119026 -0.449233 -2.038238 -0.268279 -0.225334   
1775 -0.433045  3.216018  2.011168 -0.229289 -1.509356 -1.166806 -2.852438   
1776 -0.525867 -1.154642 -1.889820  0.953330  0.807079 -1.084716  1.495888   
1777  5.106682 -0.289142  0.341407 -1.773522 -2.469449  1.596730  0.885043   
1778  5.900098 -1.710240  1.858915  0.171252 -4.529246  4.714809  0.440309   
1779  1.597139  4.676427  0.469293 -0.503400 -0.074205 -1.780277 -2.551041   
1780 -5.137834 -0.191049  2.223967  2.046426 -0.885013  3.406910 -0.342174   
1781 -1.416098 -1.031485  1.196076  0.841545 -2.197925  2.483192  0.573311   
1782 -4.272989 -1.355840  3.059714  0.367666  1.045035  0.747249  0.006419   
1783 -3.136887 -1.411700  2.238424 -0.085145  0.779780  0.689977 -1.289870   
1784  1.568544 -0.438603 -1.840596 -0.847231  0.413571 -1.193725  2.474063   
1785  0.058277  1.978137  1.807599  1.282992 -1.856847 -0.847032 -3.167596   
1786 -0.711454  0.253346 -2.934788

In [108]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860155,
       0.0421412 , 0.03942083, 0.03389381, 0.02998221, 0.02932003,
       0.02781805, 0.02577055, 0.02275303, 0.0222718 , 0.02165229,
       0.01914167, 0.01775547, 0.01638069, 0.0159646 , 0.01489191,
       0.01347969, 0.01271931, 0.01165837, 0.01057646, 0.00975316,
       0.00944555, 0.00863013, 0.00836635, 0.00797689, 0.0074647 ,
       0.00725558, 0.00691884, 0.00653837, 0.00640779, 0.0059137 ,
       0.0057111 , 0.00523158, 0.00481507, 0.00453366, 0.0042283 ])

In [109]:
from sklearn.model_selection import train_test_split

In [110]:
principalDf_train,principalDf_test,y_train,y_test = train_test_split(principalDf,y,test_size = 0.3)

In [111]:

model=LogisticRegression()
model.fit(principalDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [112]:
pred=model.predict(principalDf_test)
pred

array([9, 7, 1, 5, 4, 4, 6, 7, 1, 8, 7, 2, 9, 8, 0, 5, 4, 9, 2, 9, 7, 1,
       9, 4, 2, 7, 8, 1, 2, 0, 6, 6, 4, 2, 4, 9, 7, 8, 8, 2, 4, 3, 0, 5,
       6, 9, 2, 5, 9, 7, 5, 5, 4, 9, 1, 1, 6, 5, 4, 4, 8, 2, 8, 5, 1, 8,
       0, 6, 5, 7, 8, 0, 2, 8, 1, 5, 0, 8, 4, 3, 7, 0, 7, 5, 2, 7, 8, 2,
       7, 3, 3, 3, 6, 4, 0, 1, 8, 2, 3, 3, 3, 0, 7, 7, 2, 6, 9, 8, 2, 8,
       9, 3, 0, 7, 1, 6, 7, 6, 2, 2, 1, 6, 7, 9, 0, 7, 4, 2, 2, 8, 8, 0,
       4, 2, 8, 9, 3, 1, 5, 1, 4, 2, 8, 9, 7, 0, 6, 6, 9, 7, 3, 4, 7, 1,
       3, 7, 2, 6, 2, 8, 4, 8, 9, 9, 5, 1, 7, 9, 6, 5, 2, 3, 7, 6, 6, 1,
       6, 2, 7, 1, 1, 4, 6, 8, 5, 0, 8, 2, 8, 1, 0, 1, 2, 4, 0, 2, 3, 3,
       1, 7, 3, 7, 1, 8, 0, 0, 5, 8, 1, 0, 5, 1, 1, 1, 2, 9, 1, 6, 2, 4,
       6, 1, 7, 4, 3, 2, 2, 0, 6, 5, 6, 6, 8, 7, 9, 0, 9, 4, 7, 2, 4, 0,
       0, 8, 8, 3, 2, 7, 9, 2, 4, 9, 3, 4, 8, 6, 7, 3, 0, 9, 0, 6, 9, 8,
       8, 3, 1, 4, 9, 7, 8, 4, 2, 9, 8, 0, 0, 2, 2, 0, 0, 7, 2, 5, 1, 0,
       8, 6, 3, 3, 8, 9, 7, 4, 5, 0, 1, 8, 0, 4, 1,

In [113]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9444444444444444

In [114]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.98      0.98      0.98        55
          1       0.90      0.90      0.90        60
          2       1.00      1.00      1.00        63
          3       0.96      0.92      0.94        50
          4       1.00      0.95      0.97        55
          5       0.96      0.96      0.96        48
          6       0.94      0.98      0.96        52
          7       0.96      1.00      0.98        47
          8       0.89      0.89      0.89        53
          9       0.86      0.88      0.87        57

avg / total       0.94      0.94      0.94       540



In [115]:
from sklearn.metrics import confusion_matrix

In [116]:
confusion_matrix(y_test,pred)

array([[54,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 54,  0,  1,  0,  0,  1,  0,  0,  4],
       [ 0,  0, 63,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 46,  0,  1,  0,  0,  2,  1],
       [ 0,  1,  0,  0, 52,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0, 46,  0,  0,  0,  2],
       [ 0,  1,  0,  0,  0,  0, 51,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 47,  0,  0],
       [ 0,  3,  0,  1,  0,  0,  1,  0, 47,  1],
       [ 1,  1,  0,  0,  0,  1,  0,  2,  2, 50]], dtype=int64)