In [7]:
# Question 1
# importing the required libraries
import numpy as np
import math
a=np.random.random((10,1))
print(a)

[[0.37910123]
 [0.21153994]
 [0.37671808]
 [0.49248191]
 [0.81432315]
 [0.9587378 ]
 [0.10190735]
 [0.4774099 ]
 [0.06942724]
 [0.041121  ]]


In [4]:
a.mean() #calculating mean


0.5117733261638776

In [5]:
# Question 2

b=np.random.random((20,1))

In [6]:
print(b)

[[0.821247  ]
 [0.03400632]
 [0.48039282]
 [0.62834126]
 [0.13322962]
 [0.63436748]
 [0.56609991]
 [0.97515987]
 [0.46869301]
 [0.65993537]
 [0.63272673]
 [0.58376031]
 [0.75587267]
 [0.19684775]
 [0.2883885 ]
 [0.34508042]
 [0.32912061]
 [0.98825331]
 [0.80026919]
 [0.66481395]]


In [7]:
b.var()   #calculating variance

0.06667584192700249

In [8]:
b.std()  #calculating standard deviation

0.25821665695110085

In [8]:
# Question 3

A=np.random.random((10,20))
print(type(A))
print(A)

<type 'numpy.ndarray'>
[[0.78614707 0.1113131  0.79151126 0.1836334  0.57275705 0.61537172
  0.43426139 0.58591612 0.22612515 0.48685859 0.9868533  0.3566549
  0.69365462 0.60991401 0.84816207 0.86087827 0.68342763 0.90298877
  0.71480184 0.99222677]
 [0.25217754 0.78874942 0.42466925 0.43117076 0.43349849 0.42187429
  0.04996088 0.18346407 0.06611435 0.86400236 0.26085868 0.6865313
  0.2685613  0.34119158 0.22458108 0.03036415 0.72656448 0.34242218
  0.63503598 0.83787132]
 [0.79885916 0.54658972 0.34839526 0.22780194 0.19052263 0.27758254
  0.8496943  0.57176529 0.65433262 0.95792151 0.63054105 0.88597841
  0.88276736 0.21108749 0.63297035 0.12481336 0.71020641 0.1954964
  0.98436737 0.84918858]
 [0.91496189 0.04116165 0.37070177 0.31223792 0.45151164 0.04436316
  0.5608217  0.33795758 0.65812009 0.11699799 0.87151054 0.08495696
  0.74787995 0.52655053 0.900528   0.86728025 0.01275137 0.58198781
  0.12337579 0.02331405]
 [0.81838007 0.30678828 0.97531537 0.17229211 0.08753546 0.52368

In [9]:
B=np.random.random((20,25))
print(B)

[[0.284784   0.16003381 0.75975542 0.67608773 0.95726209 0.54921094
  0.17248739 0.78131241 0.49684296 0.08921825 0.05786688 0.27032762
  0.99712515 0.48356258 0.65170603 0.4779341  0.66957648 0.44932808
  0.05972597 0.41021069 0.23864946 0.64309227 0.13831934 0.16529598
  0.02363232]
 [0.60538804 0.95341591 0.38553612 0.28872619 0.44683506 0.49241702
  0.1292622  0.63651478 0.40663889 0.74873131 0.03909436 0.55212876
  0.61298922 0.09815439 0.12313545 0.23578595 0.49064161 0.09486192
  0.9113969  0.55372099 0.10672236 0.36755637 0.23459861 0.18978973
  0.5126682 ]
 [0.686688   0.29681726 0.50665408 0.50097798 0.64071329 0.93070997
  0.68422677 0.53150578 0.8029829  0.59895037 0.20734288 0.89133006
  0.76576612 0.00455114 0.902161   0.00630432 0.07116067 0.12141085
  0.38611662 0.46243918 0.21442109 0.93180617 0.02982548 0.78559452
  0.29160503]
 [0.72469325 0.79791893 0.14553109 0.51301726 0.56605381 0.68855342
  0.65985593 0.00119982 0.98068522 0.70488759 0.99037055 0.79391849
  0.44

In [16]:
C=np.dot(A,B) #stores the matrix multiplication of two matrices

In [17]:
print(C)

[[5.29583994 5.78503937 5.48383253 5.40901156 4.99907589 5.06373177
  3.98942525 5.15876476 4.54928513 5.11458135 5.67205477 4.67396498
  5.54229195 5.11985198 4.43055005 5.05189134 4.86369624 5.50774075
  4.65225023 3.10495121 5.1741924  4.63225534 5.11255264 4.85159045
  4.04987083]
 [5.31236067 5.7980118  6.53923615 5.32468689 5.40265339 5.5914529
  4.08223297 5.17907928 5.2390229  5.33360657 5.66386211 5.50764935
  6.06652173 5.50865371 3.74346217 5.00451036 4.96863424 6.18634302
  5.41692565 3.22088657 6.05069144 5.14138376 5.66467133 4.88735045
  4.6420697 ]
 [6.14750025 6.95329741 6.85182728 5.64474373 5.23861205 5.62199871
  4.53483333 6.15182934 5.66414786 5.70283173 6.58617262 5.36583848
  6.32883    6.207984   5.13835432 6.17725026 5.31886811 7.08074051
  6.33088724 4.2413271  6.09854018 5.47537004 5.39688083 5.56290744
  5.18513945]
 [5.83015298 6.93686331 7.00246192 5.5864889  5.11505097 6.3943948
  5.24621129 5.62091737 6.31253762 6.1243331  6.89961152 4.80584398
  6.5057

In [19]:
print(C.shape) #shape of matrix C

(10L, 25L)


In [20]:
print(C.sum()) #sum of  all the elements of matrix C

1211.719079981639


In [24]:
# Question 4

A=np.arange(10).reshape(10,1)
print(n)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [40]:
def f(x):
    return 1 /(1 + math.exp(-x)) 

np.apply_along_axis(f, 1, A)  


array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])