In [43]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
%matplotlib inline
from sklearn.svm import SVC

In [6]:
from sklearn.datasets import load_wine

In [8]:
wine=load_wine()
x=(wine.data)
y=(wine.target)


In [9]:
x.shape,y.shape

((178L, 13L), (178L,))

In [12]:
from sklearn.ensemble import BaggingClassifier

In [13]:
from sklearn import tree

In [14]:
model=tree.DecisionTreeClassifier()

In [15]:
num_trees=100

In [16]:
model1=BaggingClassifier(base_estimator=model)

In [17]:
model1

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [20]:
model1.fit(x_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [21]:
pred=model1.predict(x_test)

In [24]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9722222222222222

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         7
          1       1.00      0.93      0.97        15
          2       0.93      1.00      0.97        14

avg / total       0.97      0.97      0.97        36



In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
confusion_matrix(y_test,pred)

array([[ 7,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 14]], dtype=int64)

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
model2=RandomForestClassifier(random_state=1,max_depth=10 )

In [29]:
model2.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [31]:
pred1=model2.predict(x_test)

In [32]:
metrics.accuracy_score(y_test,pred1)

0.9444444444444444

In [33]:
print(classification_report(y_test,pred1))

             precision    recall  f1-score   support

          0       0.88      1.00      0.93         7
          1       1.00      0.87      0.93        15
          2       0.93      1.00      0.97        14

avg / total       0.95      0.94      0.94        36



In [34]:
confusion_matrix(y_test,pred1)

array([[ 7,  0,  0],
       [ 1, 13,  1],
       [ 0,  0, 14]], dtype=int64)

In [35]:
from sklearn.ensemble import GradientBoostingClassifier

In [37]:
model3=GradientBoostingClassifier()
model3

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [38]:
model3.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [39]:
pred2=model3.predict(x_test)

In [40]:
metrics.accuracy_score(y_test,pred2)

0.9166666666666666

In [41]:
confusion_matrix(y_test,pred2)

array([[ 6,  1,  0],
       [ 1, 14,  0],
       [ 0,  1, 13]], dtype=int64)

In [42]:
print(classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       0.86      0.86      0.86         7
          1       0.88      0.93      0.90        15
          2       1.00      0.93      0.96        14

avg / total       0.92      0.92      0.92        36



In [44]:
model4=LogisticRegression()
model5=tree.DecisionTreeClassifier()
model6=SVC()

In [45]:
estimators=[]

In [48]:
estimators.append(('logistic',model4))
estimators.append(('cart',model5))
estimators.append(('svm',model6))

In [49]:
from sklearn.ensemble import VotingClassifier

In [50]:
ensemble=VotingClassifier(estimators)

In [52]:
ensemble.fit(x_train,y_train)

VotingClassifier(estimators=[('logistic', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('cart',...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [54]:
pred4=ensemble.predict(x_test)

C:\Users\Dell\Anaconda2\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [55]:
metrics.accuracy_score(y_test,pred4)

0.9722222222222222

In [56]:
confusion_matrix(y_test,pred4)

array([[ 7,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 13]], dtype=int64)

In [57]:
print(classification_report(y_test,pred4))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         7
          1       0.94      1.00      0.97        15
          2       1.00      0.93      0.96        14

avg / total       0.97      0.97      0.97        36

